version: "3"
services:
  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   restart: unless-stopped
  #   volumes:
  #     - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
  #     #DESCOMENTAR CASO QUEIRA CUSTOMIZAR O OPCACHE DO PHP
  #     #- ./PHP7fpm/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
  #     #- ./Logs/Nginx:/var/log/nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - frontend
  
  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      #- ./ssl:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  cad:
    container_name: cad
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - backend
      - internal
    volumes:
      - ./volumes/cad:/var/www/html

  db:
    container_name: db 
    restart: unless-stopped
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cad
      MYSQL_DATABASE: db_clientes
      MYSQL_PASSWORD: cad
      MYSQL_USER: cad
      TZ: America/Campo_Grande
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - internal

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  internal:
    driver: bridge
